name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
     runs-on: ubuntu-latest
     steps:
      - name: Print Greeting
        run: echo "Hello github actions"
      - name: Multi Line
        run: |
          echo "first output"
          echo "second output"
      - name: Print bye
        run: echo "Good bye gha"
        
